services:
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 8080:8080
    volumes:
      - ./server/.env:/app/.env
    networks:
      server-network:
        ipv4_address: 192.168.1.101

  client:
    container_name: client
    build:
      context: ./client
    volumes:
      - ./client/.env:/app/.env
    networks:
      server-network:
        ipv4_address: 192.168.1.102

networks:
  server-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

